### ISSUE TITLE
running on custom data

### ISSUE THREAD

**Issue by carlosedubarreto** [wutong16/Voxurf#11]
I'm trying to run on custom data, but the information provided on the document seems to be lacking information.

I was able to execute the scripts that gives me a folder with these folder/files
![image](https://user-images.githubusercontent.com/4061130/229577327-68f21327-5026-4588-8264-5a44b644c3ad.png)

when executing the script to run on the custom data, I used this one
`python run.py --config configs/custom_e2e/fine.py -p exp --sdf_mode voxurf_fine --scene castelo --render_only --mesh_from_sdf`

After solving new error that showd up, I've got stuck on a new problem where I cant find any info about it.

It complains about a file `cameras_sphere.npz` that i cant find anywhere how to make it.

I even when to th IDR repository, thiking that there might have the answer, but from what I saw, their script doesnt seem to solve the issue, because I saw that they show how to create only the `camera.npz` and not the `cameras_sphere.npz`

Can someone please give moe some more directions?
thanks

**Comment by carlosedubarreto** [comment]
found a solution on this link 
[generate_camera_sphere_from_colmap_data.zip](https://github.com/wutong16/Voxurf/files/11140877/generate_camera_sphere_from_colmap_data.zip)

https://github.com/Totoro97/NeuS/issues/8

I'm using this code to generate the camera_sphere.npz from the colmap (using the instructions on voxurf page)

**Comment by carlosedubarreto** [comment]
in reality there was a problem when I run the script
`preprocess_cameras.py `
when  I executed it correctly, it generated the camera_sphere.npz

**Comment by hanjoonwon** [comment]
> in reality there was a problem when I run the script `preprocess_cameras.py ` when I executed it correctly, it generated the camera_sphere.npz

same problem how to solve?? i run bash run_process_video.sh /home/xiangyue/joonwon/Voxurf/data/bat/
bash run_convert_camera.sh /home/xiangyue/joonwon/Voxurf/data/bat/ 
when i use run_convert_camera.sh  got that error
