### ISSUE TITLE
Bad result on DTU24 without mask

### ISSUE THREAD

**Issue by adkAurora** [wutong16/Voxurf#15]
![image](https://user-images.githubusercontent.com/30972697/232987646-cb8a7578-335a-4a58-b79c-ab36af85462f.png)
The result is different from the one in the paper,  with many depressions on the roof surface.

**Comment by wutong16** [comment]
Hi. We would like to acknowledge that the performance of the algrithm drops in the absence of masks, which is reflected in our results as demonstrated in the tables. In particular, scan 24's performance is sensitive to the presence of masks, with its Chamfer Distance increasing from 0.65 (with masks) to 0.72 (without masks). The quantitative and qualitative comparisons in the main paper are under the w/ mask setting.
