### ISSUE TITLE
what is white_list?

### ISSUE THREAD

**Issue by pyni** [wutong16/Voxurf#16]
Hi. I wonder what is white_list?
in your config files, it shows:
white_list = [24, 40, 110]
black_list = [37, 55, 63, 65, 69, 83, 97, 105, 106, 114, 118, 122]

But for dtu_scan24, dtu_scan40 and dtu_scan110, the background for their masks are still black:
![image](https://user-images.githubusercontent.com/18031767/233262530-45602bad-5d08-4b29-831a-a94b41176a78.png)
So I think they still belong to black_list, right?

**Comment by wutong16** [comment]
Hi, for all the masks, the foreground is white, and the background is black. white_list means that after we remove the background of the original image, we save the image with an RGB foreground and a white background.
