### ISSUE TITLE
GPU out of memory 

### ISSUE THREAD

**Issue by pyni** [wutong16/Voxurf#17]
Hi, Thanks for your code. I have met one problem.
when I run the coarse stage, it works.
But when I run the  fine stage(even independently), it shows GPU out of memory :
 
![image](https://user-images.githubusercontent.com/18031767/233819032-288267b0-5d4c-4a5a-838c-d3b91b017ed4.png)

I have tried to decrease the number of batch size (N_rand) in configs/default_fine_s.py, but it doesn't work.

Do you have any suggestions?
Thanks.

**Comment by wutong16** [comment]
Hi @pyni, sorry for the late reply. 
Decreasing the N_rand or using a lower resolution for the grid [here](https://github.com/wutong16/Voxurf/blob/main/configs/dtu_e2e/fine.py#LL61C5-L62C16) would alleviate the problem, while the results may also be affected at the same time. The OOM problem usually occurs at around 15,000 iters during the fine stage, where the grid resolution is upscaled to 256^3.
