### ISSUE TITLE
Calculate ground truth depth

### ISSUE THREAD

**Issue by zhirui-gao** [wutong16/Voxurf#20]
https://github.com/wutong16/Voxurf/blob/ef64baad85a873a2dfa44957803426544d397e4c/lib/voxurf_coarse.py#LL597C34-L597C34
Hi,
I notice that the depth is calculated using step_id . `weights * step_id * stepdist`
Does t_min need to be added to calculate the true depth?
Best regards.

**Comment by wutong16** [comment]
Hi @zhirui-ga.
Yes, to calculate the absolute depth, we should add `t_min` to the current depth.
