### ISSUE TITLE
Questions about mask

### ISSUE THREAD

**Issue by vgrau98** [wutong16/Voxurf#23]
Hi, first, thanks for you great work !
I have some questions about mask in voxurf method:

1. How the mask files are used in the training process (ray sampling ? Loss ?). After looking at the code it seems that they are only used for the evaluation step?  

2. Is the mask strategy with the geometry extraction init from DVGO can be applied/is relevant to implicit methods (either fully implicit or with explicit features) ? 

Thank you !

**Comment by wutong16** [comment]
Hi, thank you for giving attention to our work.

1. The mask is also used for sampling following DVGO , as defined [here](https://github.com/wutong16/Voxurf/blob/main/lib/voxurf_coarse.py#L865).

2. If I understand your question correctly, you are asking whether we can use DVGO initialization in other implicit models. The answer is yes. For an indirect application, you may utilize the initialized mask cache to restrict the sampling strategy in any other model, which could potentially eliminate numerous redundant sampling pointsand implicitly constrain the initial shape.
